if(!this.JSON)this.JSON={};
(function(){function d(a){return a<10?"0"+a:a}function f(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(b){var c=r[b];return typeof c==="string"?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function j(a,b){var c,e,i,n,q=g,o,k=b[a];if(k&&typeof k==="object"&&typeof k.toJSON==="function")k=k.toJSON(a);if(typeof p==="function")k=p.call(b,a,k);switch(typeof k){case "string":return f(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);
case "object":if(!k)return"null";g+=l;o=[];if(Object.prototype.toString.apply(k)==="[object Array]"){n=k.length;for(c=0;c<n;c+=1)o[c]=j(c,k)||"null";i=o.length===0?"[]":g?"[\n"+g+o.join(",\n"+g)+"\n"+q+"]":"["+o.join(",")+"]";g=q;return i}if(p&&typeof p==="object"){n=p.length;for(c=0;c<n;c+=1){e=p[c];if(typeof e==="string")if(i=j(e,k))o.push(f(e)+(g?": ":":")+i)}}else for(e in k)if(Object.hasOwnProperty.call(k,e))if(i=j(e,k))o.push(f(e)+(g?": ":":")+i);i=o.length===0?"{}":g?"{\n"+g+o.join(",\n"+g)+
"\n"+q+"}":"{"+o.join(",")+"}";g=q;return i}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var m=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,l,r={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},p;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,b,c){var e;l=g="";if(typeof c==="number")for(e=0;e<c;e+=1)l+=" ";else if(typeof c==="string")l=c;if((p=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw new Error("JSON.stringify");return j("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(i,n){var q,o,k=i[n];if(k&&typeof k==="object")for(q in k)if(Object.hasOwnProperty.call(k,q)){o=c(k,q);if(o!==undefined)k[q]=o;else delete k[q]}return b.call(i,n,k)}var e;a=String(a);m.lastIndex=0;if(m.test(a))a=a.replace(m,function(i){return"\\u"+("0000"+i.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){e=eval("("+a+")");return typeof b==="function"?c({"":e},""):e}throw new SyntaxError("JSON.parse");}})();
var boxes={intersect:function(d,f,j){return j?d.top<=f.bottom&&f.top<=d.bottom:d.left<=f.right&&f.left<=d.right},overlap:function(d,f){return this.intersect(d,f,true)&&this.intersect(d,f,false)},left_of:function(d,f){return d.right<f.left},above:function(d,f){return d.bottom<f.top},to_string:function(d){return"{ left: "+d.left+" right: "+d.right+" top: "+d.top+" bottom:"+d.bottom+"}"}};
function BSPTree(){function d(a,b){return b.horizontal?b.y>a.top&&b.y<=a.bottom:b.x>a.left&&b.x<=a.right}function f(a,b){var c={lt:$.extend({},a),gt:$.extend({},a)};if(b.horizontal){c.lt.bottom=b.y-1;c.gt.top=b.y}else{c.gt.left=b.x;c.lt.right=b.x-1}j(c.lt);j(c.gt);return c}function j(a){a.width=a.right-a.left+1;a.height=a.bottom-a.top+1}function m(a,b){if(l(b))return g(a,b);else if(r(b)){if(d(a,b)){var c=f(a,b);b.lt=m(c.lt,b.lt);b.gt=m(c.gt,b.gt)}else if(b.horizontal?b.y>a.bottom:b.x>a.right)b.lt=
m(a,b.lt);else b.gt=m(a,b.gt);return b}throw"tree should only contain vectors or boxes";}function h(a,b){if(l(b))return[b];else if(r(b))if(d(a,b)){var c=f(a,b);return h(c.lt,b.lt).concat(h(c.gt,b.gt))}else return(b.horizontal?b.y>a.bottom:b.x>a.right)?h(a,b.lt):h(a,b.gt);throw"tree should only contain vectors or boxes";}function g(a,b){if(boxes.intersect(b,a,false)){if(!boxes.intersect(b,a,true))return boxes.above(b,a)?{x:a.left,y:a.top,horizontal:true,lt:b,gt:a}:{x:b.left,y:b.top,horizontal:true,
lt:a,gt:b}}else return boxes.left_of(b,a)?{x:a.left,y:a.top,horizontal:false,lt:b,gt:a}:{x:b.left,y:b.top,horizontal:false,lt:a,gt:b};throw"intersecting boxes not supported current: "+boxes.to_string(b)+"  new: "+boxes.to_string(a);}function l(){for(var a=0;a<arguments.length;a++)if(!p(arguments[a],"top","bottom","left","right"))return false;return true}function r(){for(var a=0;a<arguments.length;a++)if(!p(arguments[a],"x","y","horizontal"))return false;return true}function p(){for(var a=arguments[0],
b=1;b<arguments.length;b++)if(a[arguments[b]]==undefined)return false;return true}return{put:function(a){if(this.head==null)this.head=a;else if(l(this.head))this.head=g(a,this.head);else m(a,this.head)},find_adjacent:function(a){if(this.head==null)return null;return h(a,this.head)}}}
function SpiralLayout(){function d(a,b,c){return c?a+b:a-b}function f(a,b,c,e){a=h(a,function(n){return boxes.overlap(n,b)});if(a.t.length>0){var i=c.expanding.positive;e.expanding=d(g(a.t,c.expanding.to,i),1,i)}else j(a.f,b,c,e)}function j(a,b,c,e){a=h(a,function(n){return boxes.intersect(n,b,c.expanding.horizontal)});if(a.t.length>0){var i=c.expanding.positive;e.expanding=d(g(a.t,c.expanding.to,i),1,i)}else m(a.f,b,c,e)}function m(a,b,c,e){e.expanding=g(a,c.expanding.from,!c.expanding.positive);
l(b,c,e);a=h(a,function(n){return boxes.intersect(n,b,c.moving.horizontal)});if(a.t.length>0){var i=c.moving.positive;e.moving=d(g(a.t,c.moving.to,i),1,i)}}function h(a,b){for(var c={t:[],f:[]},e=0;e<a.length;e++)(b(a[e])?c.t:c.f).push(a[e]);return c}function g(a,b,c){return a.reduce(function(e,i){return(c?e<i[b]:e>i[b])?i[b]:e},a[0][b])}function l(a,b,c){a[b.moving.from]=c.moving;a[b.expanding.from]=c.expanding;a[b.moving.to]=d(a[b.moving.from],b.moving.horizontal?a.width:a.height,b.moving.positive);
a[b.expanding.to]=d(a[b.expanding.from],b.expanding.horizontal?a.width:a.height,b.expanding.positive)}var r={right:{expand:"up",next:"down"},down:{expand:"right",next:"left"},left:{expand:"down",next:"up"},up:{expand:"left",next:"right"}},p={right:{from:"left",to:"right",horizontal:true,positive:true},left:{from:"right",to:"left",horizontal:true,positive:false},down:{from:"top",to:"bottom",horizontal:false,positive:true},up:{from:"bottom",to:"top",horizontal:false,positive:false}};return{top:0,bottom:0,
left:0,right:0,direction:"",last_inner:0,last_moving:0,space:BSPTree(),add:function(a,b){var c={top:0,bottom:0,left:0,right:0,width:a,height:b};if(this.direction==""){var e=Math.floor(c.height/2),i=Math.floor(c.width/2);c.top=-e;c.left=-i;c.right=c.width-i;c.bottom=c.height-e;this.top=c.top;this.left=c.left;this.bottom=c.bottom;this.right=c.right;this.last_moving=c.top-1;this.last_inner=c.right+1;this.direction="down"}else{e=$.extend({},r[this.direction]);e.moving=p[this.direction];e.expanding=p[e.expand];
i={};i.moving=d(this.last_moving,1,e.moving.positive);i.expanding=d(this.last_inner,-1,e.expanding.positive);l(c,e,i);var n=this.space.find_adjacent(c);f(n,c,e,i);l(c,e,i);this.last_moving=c[e.moving.to];this.last_inner=c[e.expanding.from];if(e.moving.positive?this[e.moving.to]<c[e.moving.to]:this[e.moving.to]>c[e.moving.to]){this.direction=e.next;this.last_moving=c[e.expanding.from];this.last_inner=d(this[e.moving.to],1,e.moving.positive);this[e.moving.to]=c[e.moving.to]}if(e.expanding.positive?
this[e.expanding.to]<c[e.expanding.to]:this[e.expanding.to]>c[e.expanding.to])this[e.expanding.to]=c[e.expanding.to]}this.space.put(c);return c}}}var PADDING=11,MARGIN=10;function log(d){$("#debug").text(d)}function stopEvent(d){d.stopPropagation();d.preventDefault()}function startDrag(d){var f=$("#body");f.data("cursor",{mousedown:true,x:d.pageX,y:d.pageY});f.css("cursor","-moz-grabbing");stopEvent(d)}
function stopDrag(d){var f=$("#body"),j=f.data("cursor");j.mousedown=false;f.data("cursor",j);f.css("cursor","-moz-grab");stopEvent(d)}
function drag(d){var f=$("#body");log("moving the mouse");var j=f.data("cursor"),m=f.data("position");if(j.mousedown){f=d.pageX-j.x;var h=d.pageY-j.y;j.x=d.pageX;j.y=d.pageY;m.offsetX+=f;m.offsetY+=h;log(d.pageX+", "+d.pageY);$(".item").each(function(){var g=$(this),l=g.data("left"),r=g.data("top");g.css("left",l+m.offsetX+"px");g.css("top",r+m.offsetY+"px")})}stopEvent(d)}
$(window).resize(function(){var d=$(window),f=$("#header");$("#cover").css({height:d.height()+"px",width:d.width()+"px"});$("#body").css("height",d.height()-f.height()+"px")});
$(function(){(new Image).src="/images/loading_btn.gif";var d=function(h,g){h.data("defaultValue",g);h.val(g);h.focus(function(){var l=$(this);l.val()==l.data("defaultValue")&&l.val("")});h.blur(function(){var l=$(this);l.val()==""&&l.val(l.data("defaultValue"))})};d($("#coll-name"),wall.name==""?"Name your collection":wall.name);d($("#img-url"),"Paste your image URLs here");$("#collname form").submit(function(h){$("#message").slideUp("fast");var g=$(this);g.find(".button").attr("disabled","true").addClass("loading");
wall.name=$("#coll-name").val();$.ajax({type:g.attr("method"),url:g.attr("action"),data:JSON.stringify(wall),success:function(){d($("#coll-name"),wall.name);$("title").text(wall.name+" - Scrwall");g.find(".button").removeAttr("disabled").removeClass("loading")}});h.preventDefault();return false});$("#closemsg").click(function(){$("#message").slideUp("fast")});$("#imgurl form").submit(function(h){$("#message").slideUp("fast");var g=$(this);g.find(".button").attr("disabled","true").addClass("loading");
var l={url:$("#img-url").val()};$.ajax({type:g.attr("method"),url:g.attr("action"),data:JSON.stringify(l),success:function(){addItem(l.url);$("#img-url").val("").trigger("blur");g.find(".button").removeAttr("disabled").removeClass("loading")},error:function(){g.find(".button").removeAttr("disabled").removeClass("loading");$("#msgtxt").text("The url you provided didn't quite work could you try again?");$("#message").slideDown("fast")}});h.preventDefault();return false});$(".feedback").click(function(h){$("#overlay").fadeIn("fast");
h.preventDefault();return false});$("#close-feedback").click(function(h){$("#overlay").css("display","none");h.preventDefault();return false});var f=$("#body"),j=$(window),m=$("<div>",{id:"cover",css:{height:j.height()+"px",width:j.width()+"px","z-index":1E3,position:"absolute"},click:function(){$('input[type="text"]').blur()},mousedown:startDrag,mouseout:stopDrag,mouseup:stopDrag,mousemove:drag});f.css("height",j.height()-$("#header").height()+"px");f.append(m);f.data("position",{offsetX:f.width()/
2,offsetY:f.height()/2});f.data("cursor",{mousedown:false,x:0,y:0});f.data("layout",SpiralLayout(PADDING,MARGIN));$.each(items,function(){addItem(this)})});function addItem(d){var f=new Image;$(f).attr({src:d,alt:"Collection Item"});$(f).load(loadImage)}
function loadImage(){var d=$("<div>",{"class":"item"}).append($(this)),f=$("#body"),j=f.data("layout"),m=f.data("position"),h=(MARGIN+PADDING)*2;h=j.add(this.width+h,this.height+h);j=h.top+MARGIN;h=h.left+MARGIN;d.css("top",j+m.offsetY+"px");d.css("left",h+m.offsetX+"px");d.data("top",j);d.data("left",h);f.append(d)};

