application: scr-wall
version: 3
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  expiration: 7d

- url: /static
  static_dir: static
  expiration: 7d

- url: /images
  static_dir: images
  expiration: 7d

- url: /test
  static_dir: test

- url: /res/.*
  script: resources.py

- url: /feedback.*
  script: feedback_view.py
  login: admin

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: view.py
