application: scrwall
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /font-face
  static_dir: font-face

- url: /test
  static_dir: test

- url: /res/.*
  script: resources.py

- url: /.*
  script: view.py