application: scr-wall
version: 2
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
  expiration: 7d

- url: /static
  static_dir: static
  expiration: 7d

- url: /images
  static_dir: images
  expiration: 7d

- url: /test
  static_dir: test

- url: /res/.*
  script: resources.py

- url: /.*
  script: view.py
